FROM node:8

ARG APP_EMAIL
ARG APP_ENV
ARG APP_NAME
ARG APP_PORT
ARG IMAGE_TAG
ARG APP_URL
ARG DB_DATABASE
ARG DB_HOST
ARG DB_PASSWORD
ARG DB_PORT
ARG DB_USER
ARG JWT_ACCESS_TOKEN_EXP
ARG JWT_SECRET
ARG RECAPTCHA_SECRET
ARG SENDGRID_API_KEY

ENV APP_EMAIL=$APP_EMAIL \
    APP_ENV=$APP_ENV \
    APP_NAME=$APP_NAME \
    APP_PORT=$APP_PORT \
    IMAGE_TAG=$IMAGE_TAG \
    APP_URL=$APP_URL \
    DB_DATABASE=$DB_DATABASE \
    DB_HOST=$DB_HOST \
    DB_PASSWORD=$DB_PASSWORD \
    DB_PORT=$DB_PORT \
    DB_USER=$DB_USER \
    JWT_ACCESS_TOKEN_EXP=$JWT_ACCESS_TOKEN_EXP \
    JWT_SECRET=$JWT_SECRET \
    RECAPTCHA_SECRET=$RECAPTCHA_SECRET \
    SENDGRID_API_KEY=$SENDGRID_API_KEY

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

RUN npm install knex -g && npm install pm2 -g

COPY . .

RUN npm run build

# ENTRYPOINT touch .env && \
#        echo APP_EMAIL=$APP_EMAIL >> .env && \
#        echo APP_ENV=$APP_ENV >> .env && \
#        echo APP_NAME=$APP_NAME >> .env && \
#        echo APP_PORT=$APP_PORT >> .env && \
#        echo APP_URL=$APP_URL >> .env && \
#        echo IMAGE_TAG=$IMAGE_TAG > .env && \
#        echo DB_DATABASE=$DB_DATABASE >> .env && \
#        echo DB_HOST=$DB_HOST >> .env && \
#        echo DB_PASSWORD=$DB_PASSWORD >> .env && \
#        echo DB_PORT=$DB_PORT >> .env && \
#        echo DB_USER=$DB_USER >> .env && \
#        echo JWT_ACCESS_TOKEN_EXP=$JWT_ACCESS_TOKEN_EXP >> .env && \
#        echo JWT_SECRET=$JWT_SECRET >> .env && \
#        echo RECAPTCHA_SECRET=$RECAPTCHA_SECRET >> .env && \
#        echo SENDGRID_API_KEY=$SENDGRID_API_KEY >> .env && \
#        npm run start-production

RUN touch .env && \
        echo APP_EMAIL=$APP_EMAIL >> .env && \
        echo APP_ENV=$APP_ENV >> .env && \
        echo APP_NAME=$APP_NAME >> .env && \
        echo APP_PORT=$APP_PORT >> .env && \
        echo APP_URL=$APP_URL >> .env && \
        echo IMAGE_TAG=$IMAGE_TAG > .env && \
        echo DB_DATABASE=$DB_DATABASE >> .env && \
        echo DB_HOST=$DB_HOST >> .env && \
        echo DB_PASSWORD=$DB_PASSWORD >> .env && \
        echo DB_PORT=$DB_PORT >> .env && \
        echo DB_USER=$DB_USER >> .env && \
        echo JWT_ACCESS_TOKEN_EXP=$JWT_ACCESS_TOKEN_EXP >> .env && \
        echo JWT_SECRET=$JWT_SECRET >> .env && \
        echo RECAPTCHA_SECRET=$RECAPTCHA_SECRET >> .env && \
        echo SENDGRID_API_KEY=$SENDGRID_API_KEY >> .env

CMD [ "node", "app.js" ]
