# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Run Workflow
      id: write_file
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: '.env.production'
        encodedString: ${{ secrets.APP_ENV_VARIABLES_PRODUCTION }}
    
    # Write keys to file
    - name: Write key file
      run: for v in `cat ${{ steps.write_file.outputs.filePath }}` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done

    # AWS Creds
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    # AWS ECR Login
    - name: Amazon ECR "Login" Action for GitHub Actions
      uses: aws-actions/amazon-ecr-login@v1
    
    # Build Image
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: my-ecr-repo
        IMAGE_TAG: ${{ github.sha }}
        APP_VERSION: 0.0.1
        APP_ENV: ${{ env.APP_ENV }}
        APP_PORT: ${{ env.APP_PORT }}
        JWT_SECRET: ${{ env.JWT_SECRET }}
        JWT_ACCESS_TOKEN_EXP: ${{ env.JWT_ACCESS_TOKEN_EXP }}
        DB_ADDR: ${{ env.DB_ADDR }}
        DB_DATABASE: ${{ env.DB_DATABASE }}
        DB_USER: ${{ env.DB_USER }}
        DB_PASSWORD: ${{ env.DB_PASSWORD }}
        DB_HOST: ${{ env.DB_HOST }}
        DB_PORT: ${{ env.DB_PORT }}
        APP_NAME: ${{ env.APP_NAME }}
        APP_EMAIL: ${{ env.APP_EMAIL }}
        SENDGRID_API_KEY: ${{ env.SENDGRID_API_KEY }}
        RECAPTCHA_SECRET: ${{ env.RECAPTCHA_SECRET }}
      run: |
        docker info
        docker-compose --version
        docker-compose -f docker-compose.production.yml build
        docker-compose -f docker-compose.production.yml push

    # Logout of AWS ECR
    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
