name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Amazon ECR "Login" Action for GitHub Actions
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        APP_EMAIL: ${{ secrets.APP_EMAIL }}
        APP_ENV: ${{ secrets.APP_ENV }}
        APP_NAME: ${{ secrets.APP_NAME }}
        APP_PORT: ${{ secrets.APP_PORT }}
        APP_URL: ${{ secrets.APP_URL }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        JWT_ACCESS_TOKEN_EXP: ${{ secrets.JWT_ACCESS_TOKEN_EXP }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        export ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
        echo $ECR_REGISTRY
        export ECR_REPOSITORY=${{ github.event.repository.name }}
        echo $ECR_REPOSITORY
        export IMAGE_TAG=${{ github.sha }}
        echo $IMAGE_TAG
        docker info
        docker-compose --version
        docker-compose -f docker-compose.production.yml build
        docker-compose -f docker-compose.production.yml push
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Download and store the task definition
      run: |
        aws ecs describe-task-definition --task-definition koa-view-notes-api-task-definition > task-definition.json
        cat task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: koa-vue-notes-api
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: koa-vue-notes-api-service
        cluster: koa-vue-notes-api-cluster
        wait-for-service-stability: true

    - name: Logout of Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
